# Site settings
name: Jarrett Ang
title: Jarrett Ang | Games Programmer
description: Portfolio website
url: https://jarrettang.github.io/
baseurl: ''
email: jarrett_ang@hotmail.com
cover: https://JarrettAng.github.io/img/og.png
logo: https://JarrettAng.github.io/img/emojis/technologist.png
resume: https://JarrettAng.github.io/resume.pdf
social:
  - title: email
    url: mailto:jarrett_ang@hotmail.com
  - title: linkedin
    url: https://www.linkedin.com/in/ajjarrett/
  - title: itch.io
    url: https://jarrett-ang.itch.io/
  - title: github
    url: https://github.com/JarrettAng

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
